sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t haisoftwarevn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true haisoftwarevn/react-test npm test 
after_success:
  - docker build -t haisoftwarevn/multi-client ./client
  - docker build -t haisoftwarevn/multi-nginx ./nginx
  - docker build -t haisoftwarevn/multi-server ./server
  - docker build -t haisoftwarevn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push haisoftwarevn/multi-client 
  - docker push haisoftwarevn/multi-nginx 
  - docker push haisoftwarevn/multi-server
  - docker push haisoftwarevn/multi-worker